# Generated by Django 5.1.7 on 2025-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeePluginModel',
            new_name='EmployeeTablePluginModel',
        ),
    ]
