# Generated by Django 5.1.7 on 2025-03-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employeepluginmodel_employeetablepluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetablepluginmodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Employee (First + Last Name)'),
        ),
    ]
