# Generated by Django 5.1.7 on 2025-03-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeetablepluginmodel_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetablepluginmodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
