# Generated by Django 5.1.7 on 2025-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_facebookprofileembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofileembed',
            name='widget_id',
            field=models.CharField(default='default-widget-id', max_length=100, verbose_name='Elfsight Widget ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofileembed',
            name='widget_id',
            field=models.CharField(default='default-widget-id', max_length=100, verbose_name='Elfsight Widget ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiktokprofileembed',
            name='widget_id',
            field=models.CharField(default='default-widget-id', max_length=100, verbose_name='Elfsight Widget ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookprofileembed',
            name='page_url',
            field=models.URLField(verbose_name='https://www.facebook.com/elfsight/#'),
        ),
        migrations.AlterField(
            model_name='instagramprofileembed',
            name='username',
            field=models.CharField(max_length=100, verbose_name='susupaints'),
        ),
    ]
