# Generated by Django 5.1.7 on 2025-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_facebookprofileembed_widget_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofileembed',
            name='widget_id',
        ),
        migrations.RemoveField(
            model_name='instagramprofileembed',
            name='widget_id',
        ),
        migrations.RemoveField(
            model_name='tiktokprofileembed',
            name='widget_id',
        ),
        migrations.AlterField(
            model_name='facebookprofileembed',
            name='page_url',
            field=models.URLField(verbose_name='Facebook Page URL'),
        ),
        migrations.AlterField(
            model_name='instagramprofileembed',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Susupaints'),
        ),
    ]
