# Generated by Django 5.1.7 on 2025-04-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0010_remove_facebookprofileembed_widget_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaEmbed',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('embed_code', models.TextField(verbose_name='Embed HTML Code')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='instagramprofileembed',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='tiktokprofileembed',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='FacebookProfileEmbed',
        ),
        migrations.DeleteModel(
            name='InstagramProfileEmbed',
        ),
        migrations.DeleteModel(
            name='TikTokProfileEmbed',
        ),
    ]
