# Generated by Django 5.1.7 on 2025-04-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0011_socialmediaembed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Education', 'Education'), ('Music', 'Music'), ('Religion', 'Religion'), ('News', 'News'), ('Country', 'Country')], max_length=50)),
                ('instagram_post_link', models.URLField(blank=True, null=True)),
                ('facebook_post_link', models.URLField(blank=True, null=True)),
                ('tiktok_video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
