# Generated by Django 5.1.7 on 2025-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_creator_creatorpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='facebook_post_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='instagram_post_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tiktok_video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
