# Generated by Django 5.1.7 on 2025-05-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_googleloginbuttonpluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleLoginButtonPluginModel',
        ),
    ]
