# Generated by Django 5.1.7 on 2025-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_termspluginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='facebook_post_link',
            new_name='facebook_profile_link',
        ),
        migrations.RenameField(
            model_name='creator',
            old_name='instagram_post_link',
            new_name='instagram_profile_link',
        ),
        migrations.RenameField(
            model_name='creator',
            old_name='tiktok_video_link',
            new_name='tiktok_profile_link',
        ),
    ]
