# Generated by Django 5.1.7 on 2025-05-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0018_rename_facebook_post_link_creator_facebook_profile_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokLoginPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('button_text', models.CharField(default='Login with TikTok', max_length=100)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
