# Generated by Django 5.1.7 on 2025-06-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0020_facebookloginpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinueWithEmailPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('button_text', models.CharField(default='Continue with Email', max_length=50)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
