# Generated by Django 5.1.7 on 2025-06-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_continuewithemailpluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TikTokLoginPluginModel',
        ),
    ]
