# Generated by Django 5.1.7 on 2025-06-08 12:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_tiktokloginpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+200000000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
