# Generated by Django 5.1.7 on 2025-06-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
