# Generated by Django 5.1.7 on 2025-07-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('employees', '0027_userplatformprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('last_updated', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
