# Generated by Django 5.1.7 on 2025-08-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_linkedaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
    ]
