# Generated by Django 5.1.7 on 2025-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_buttonclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaembed',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
    ]
